FROM lcgc/postgresql:11.6
MAINTAINER Eagle Liut <eagle@dantin.me>

ENV POSTGIS_VERSION=2.5.2 POSTGIS_SHA256=225aeaece00a1a6a9af15526af81bef2af27f4c198de820af1367a792ee1d1a9

RUN set -ex \
    \
    && apk add --no-cache --virtual .fetch-deps \
        ca-certificates \
        openssl \
        tar \
    \
    && apk add --no-cache --virtual .build-deps \
        autoconf \
        automake \
        g++ \
        libtool \
        libxml2-dev \
        make \
        perl \
        postgresql-dev \
        json-c-dev \
    \
    && apk add --no-cache --virtual .build-deps-edge \
        --repository http://dl-cdn.alpinelinux.org/alpine/v3.11/community \
        --repository http://dl-cdn.alpinelinux.org/alpine/v3.11/main \
        gdal-dev \
        geos-dev \
        proj-dev \
    \
    && apk add --no-cache --virtual .postgis-rundeps \
        json-c \
    && apk add --no-cache --virtual .postgis-rundeps-edge \
        --repository http://dl-cdn.alpinelinux.org/alpine/v3.11/community \
        --repository http://dl-cdn.alpinelinux.org/alpine/v3.11/main \
        geos \
        gdal \
        proj \
    \
    && wget -O postgis.tar.gz "https://github.com/postgis/postgis/archive/$POSTGIS_VERSION.tar.gz" \
    && echo "$POSTGIS_SHA256 *postgis.tar.gz" | sha256sum -c - \
    && mkdir -p /usr/src/postgis \
    && tar \
        --extract \
        --file postgis.tar.gz \
        --directory /usr/src/postgis \
        --strip-components 1 \
    && rm postgis.tar.gz \
    && cd /usr/src/postgis \
    && ./autogen.sh \
    && ./configure \
    	--without-protobuf --without-json --without-topology --without-interrupt-tests --without-raster --without-wagyu \
    	--with-geosconfig=/usr/bin/geos-config \
    && make \
    && make install \
    && cd / \
    && rm -rf /usr/src/postgis \
    && apk del .fetch-deps .build-deps .build-deps-edge
